version: '3.6'
services:
  hello:
    image: hashicorp/http-echo
    command: ["-text", "Hello world!"]
  json-server:
      image: williamyeh/json-server
      volumes:
        - ./data:/data
      command: --watch db.json


